// catogory head asst top

export const AboutData = [
	{
		id: 1,
		category: "top",
		post: "Cheif Event Coordinator",
		name: "Soham Shahne",
		instagram: "https://www.instagram.com/sohxm_s/",
		linkdin: "",
		img: "img/Soham Shahane_CEC-min.jpeg",
	},
	{
		id: 2,
		category: "top",
		post: "Chairperson",
		name: "Anurag Joshi",
		instagram: "https://www.instagram.com/anuragpeajoshi/",
		linkdin: "",
		img: "img/Anurag Joshi.jpg",
	},
	{
		id: 3,
		category: "top",
		post: "Vice Chairperson",
		name: "Anuj Shinde",
		instagram: "https://www.instagram.com/anuj_3112/",
		linkdin: "",
		img: "img/Anuj Shinde_Vice Chairperson 1-min.jpg",
	},
	{
		id: 4,
		category: "head",
		post: "Secretary",
		name: "Vanshika Ubale",
		instagram: "https://www.instagram.com/vans_vu/",
		linkdin: "",
		img: "img/Vans vu.jpg",
	},
	{
		id: 5,
		category: "head",
		post: "Event Coordinator",
		name: "Omkar Ayare",
		instagram: "https://www.instagram.com/omkaaar07/",
		linkdin: "",
		img: "img/Omkar ayare_ event coordinator -min.jpg",
	},
	{
		id: 6,
		category: "head",
		post: "Marketing",
		name: "Sanjana Pawar",
		instagram: "https://www.instagram.com/_crazy_sanju_/",
		linkdin: "",
		img: "img/Sanjana Pawar Photo Formals-min-min.JPG",
	},
	{
		id: 7,
		category: "head",
		post: "Technical",
		name: "Adarsh Dubey",
		instagram: "https://www.instagram.com/adarshdubey108/",
		linkdin: "",
		img: "img/Adarsh Dubey - Technical head -min.JPG",
	},
	{
		id: 8,
		category: "head",
		post: "Technical",
		name: "Abdul Kabeer Shivani",
		instagram: "https://www.instagram.com/kabs225/",
		linkdin: "",
		img: "img/Abdul.jpg",
	},
	{
		id: 9,
		category: "head",
		post: "Registration",
		name: "Kaushik Gudalkar",
		instagram: "https://www.instagram.com/_itz_kaushik_10/",
		linkdin: "",
		img: "img/Kaushik Gudalkar_Registration Head-min.JPG",
	},
	{
		id: 10,
		category: "head",
		post: "Publicity",
		name: "Prasad Prabhu",
		instagram: "https://www.instagram.com/prasad_prp10_prabhu/",
		linkdin: "",
		img: "img/Prasad-min.jpg",
	},
	{
		id: 11,
		category: "head",
		post: "Creative",
		name: "Sanya Shaikh",
		instagram: "https://www.instagram.com/__.san.shine.__/",
		linkdin: "",
		img: "img/Sanya Shaikh_Creative Head-min.jpg",
	},
	{
		id: 12,
		category: "asst",
		post: "Event Coordinator",
		name: "Badal",
		instagram: "https://www.instagram.com/badallll__/",
		linkdin: "",
		img: "img/Badal edited-min.jpg",
	},
	{
		id: 13,
		category: "asst",
		post: "Event Coordinator",
		name: "Chaitanaya Dandekar",
		instagram: "https://www.instagram.com//",
		linkdin: "",
		img: "img/Chaitanaya  edited-min.jpg",
	},
	{
		id: 14,
		category: "asst",
		post: "Event Coordinator",
		name: "Devesh Shetty",
		instagram: "https://www.instagram.com/devesh_12_/",
		linkdin: "",
		img: "img/Devesh Shetty-min.jpg",
	},
	{
		id: 15,
		category: "asst",
		post: "Marketing",
		name: "Chinmay Kadam",
		instagram: "https://www.instagram.com/chinmay _11_03/",
		linkdin: "",
		img: "img/Chinmay edited-min.jpg",
	},
	{
		id: 16,
		category: "asst",
		post: "Marketing",
		name: "Pooja Patil",
		instagram: "https://www.instagram.com/poojapatil2_/",
		linkdin: "",
		img: "img/pooja patil-min.jpg",
	},
	{
		id: 17,
		category: "asst",
		post: "Technical",
		name: "Harsheet Jani",
		instagram: "https://www.instagram.com/harsheetjani_/",
		linkdin: "",
		img: "img/Harsheet jani edited-min.jpg",
	},
	{
		id: 18,
		category: "asst",
		post: "Registration",
		name: "Deepansh Londhe",
		instagram: "https://www.instagram.com/deepansh_486/",
		linkdin: "",
		img: "img/Deepansh Londhe_ Assistant Registration Head-min.jpg",
	},
	{
		id: 19,
		category: "asst",
		post: "Registration",
		name: "Aryan Jadhav",
		instagram: "https://www.instagram.com/aryan_0.0_/",
		linkdin: "",
		img: "img/Aryan Jadhav_ Assistant Registration Head-min.jpg",
	},
	{
		id: 20,
		category: "asst",
		post: "Pubilicity",
		name: "Aastha Pimple",
		instagram: "https://www.instagram.com/aastha_018/",
		linkdin: "",
		img: "img/Aastha edited.jpg",
	},
	{
		id: 21,
		category: "asst",
		post: "Celeb and Hospitality",
		name: "Aditiya Joshi",
		instagram: "https://www.instagram.com/_adityajoshiii_/",
		linkdin: "",
		img: "img/UAditiya edited-min.jpg",
	},
	{
		id: 22,
		category: "asst",
		post: "Creative",
		name: "Nimisha Marchande",
		instagram: "https://www.instagram.com/nimishhaaa/",
		linkdin: "",
		img: "img/Nimishaa edited-min.jpg",
	},
	{
		id: 23,
		category: "asst",
		post: "Creative",
		name: "Tanaya Lad",
		instagram: "https://www.instagram.com/being._reckless/",
		linkdin: "",
		img: "img/Tanaya Lad_Asst. Creative Head-min.jpg",
	},
	{
		id: 24,
		category: "asst",
		post: "Creative",
		name: "Kedar Khamkar",
		instagram: "https://www.instagram.com/_kedar07/",
		linkdin: "",
		img: "img/Kedar Khamkar _Assitant Creative Head -min.jpg",
	},
	{
		id: 25,
		category: "asst",
		post: "Digital Creative",
		name: "Arnav Pawar",
		instagram: "https://www.instagram.com/Arnav_1703_",
		linkdin: "https://www.linkedin.com/in/arnavpawar/",
		img: "img/Arnav edited-min.jpg",
	},
	{
		id: 26,
		category: "asst",
		post: "Digital Creative",
		name: "Chinmaye Bidaye",
		instagram: "https://www.instagram.com/_chinmayeeeeee/",
		linkdin: "",
		img: "img/Chinmayee Bidaye_Asst. Digital Creative Head-min.jpg",
	},
	{
		id: 27,
		category: "asst",
		post: "Digital Creative",
		name: "Agneya Pathare",
		instagram: "https://www.instagram.com/agneya_pathare/",
		linkdin:
			"https://www.linkedin.com/in/agneya-pathare/?trk=public_profile_browsemap&originalSubdomain=in",
		img: "img/Agneya .jpg",
	},
];
